.travis.yml
Makefile

Add travis build

---

README.md

Add Go Report card

---

Dockerfile

Add license to Dockerfile

---

Makefile
README.md
docker-compose.yml

Add Docker compose

---

Dockerfile

Fix Dockerfile version arg

---

README.md
docker-compose.yml

Change slack to kubernetes

---

internal/application/filesystem.go

Add port for api server access using statefulset

---

codecov.yml

Disable codecov updating commit status

---

.golangci.yml
.golangci_sample.yml
internal/application/filesystem.go
internal/types/appmetadata.go

I have removed most of the golint errors. You will need to add comments to all the exported function in the following format:
`// Add adds two given numbers and returns their value
func Add(a,b int){
return a+b
}`
Since i have less idea of your project and usage of functions, i'll the adding comments to you. I have fixed the other linting issue.
Also i have added a golang config file (.golangci.yml) which would check for golint errors using the command `golangci-lint run` in the terminal itself. I have only added golint checks in the file configs. I have also added a sample file name (.golangci_sample.yml) with other checks like gosec and errcheck which i use personally for my go projects. Please have a look over them.
Otherwise inserting the comments for each exported functions and …

Remove golint errors and add config file for golint

---

internal/application/IApplication.go
internal/application/filesystem.go
internal/types/appmetadata.go
main.go

Fix lint errors

---

.golangci.yml

Increase golint min confidence

---

main.go

Fix artifact type

---

contributing.md

Add Developer certificate to contributing.md

---

Makefile

Update golangci lint version

---

Dockerfile

Signed-off-by: Harikrishnan Balagopal <Harikrishnan.Balagopal@ibm.com>

fix build-arg so that it is in scope at the proper places

---

internal/application/filesystem.go

Signed-off-by: Harikrishnan Balagopal <Harikrishnan.Balagopal@ibm.com>

temporary fix until we add move2kube as a dependency

---

.github/workflows/build.yml
.github/workflows/prbuild.yml
.github/workflows/release.yml
Makefile
README.md

- Update discussion session with website link
- Add support for github actions

addgithubactions

---

.github/workflows/clichange.yml

Add github actions trigger for cli change

---

.github/workflows/tag.yml
README.md

- Add github actions badge
- Add tagging github action

Add github badge and tagging action

---

.github/workflows/clichange.yml

Always push image with latest tag on cli change

---

.github/workflows/release.yml

Add notification on release draft creation

---

.github/workflows/assignproject.yml

Autoassign issues to projects

---

internal/application/filesystem.go
main.go

Signed-off-by: Akash Nayak <akash19nayak@gmail.com>
Clean up Move2Kube-UI logs - https://github.com/konveyor/move2kube-api/issues/25.

Clean up logs

---

.github/workflows/assignproject.yml
.github/workflows/release.yml
.github/workflows/tag.yml
.grenrc.js

fix: refactor the release workflow to match the cli release workflow

---

.github/workflows/clichange.yml

fix: reformat cli change workflow

---

.github/workflows/clichange.yml
.github/workflows/labelpr.yml
.github/workflows/prbuild.yml

feat: label pull requests based on their title

---

Dockerfile
Makefile
cmd/move2kubeapi/move2kubeapi.go
docker-compose.yml
go.mod
go.sum
internal/application/IApplication.go
internal/move2kubeapi/move2kubeapi.go

feat: Parameterize port and add verbose option to command line

---

.github/workflows/build.yml
.github/workflows/release.yml

ci: Add support for all-in-one image build

---

Dockerfile

feat: Use fedora as base image

---

internal/application/IApplication.go
internal/application/filesystem.go
internal/move2kubeapi/move2kubeapi.go
internal/types/appmetadata.go

Signed-off-by: Akash Nayak <akash19nayak@gmail.com>
Added support for debug flag in the url to print the debug logs for move2kube `plan` and `translate` https://github.com/konveyor/move2kube-api/issues/25

feat: Add support for move2kube debug mode

---

go.mod
go.sum
internal/application/filesystem.go

Copy the source code folder to`src` folder inside the generated artifacts folder which will be downloaded as a zip file. https://github.com/konveyor/move2kube-api/issues/51
Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

feat: Download zip with both source code and new files

---

internal/application/filesystem.go

https://github.com/konveyor/move2kube-api/issues/63 Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

fix: Add Application name and the Artifact name in the logs

---

internal/application/filesystem.go

Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

fix: Copy source code only if non-empty containers directory exists

---

internal/application/filesystem.go
internal/move2kubeapi/move2kubeapi.go

fix: Prevent panic on fatal log from move2kube

---

.github/workflows/build.yml
.github/workflows/prbuild.yml
.github/workflows/release.yml
Dockerfile
Makefile

feat: compress binaries

---

.grenrc.js
README.md

chore: fix move2kube website url

---

Makefile
internal/application/filesystem.go

fix: we are copying the sources in CLI already

---

go.mod
go.sum
internal/application/filesystem.go

fix: set the app name correctly

---

Dockerfile
docker-compose.yml
internal/application/IApplication.go
internal/application/filesystem.go
internal/move2kubeapi/move2kubeapi.go

feat: provide some info for debugging purposes

---

internal/application/filesystem.go
internal/move2kubeapi/move2kubeapi.go

fix: return an error when the questions are finished and the file is deleted

---

internal/application/IApplication.go
internal/application/filesystem.go
internal/move2kubeapi/move2kubeapi.go

feat: support move2kube v0.3.0

---

Makefile
internal/application/IApplication.go
internal/application/filesystem.go
internal/application/filesystem_test.go
internal/move2kubeapi/move2kubeapi.go

feat: allow uploading the customizations folder

---

Dockerfile
Makefile
internal/application/filesystem.go

refactor: Change base image to ubi-minimal

---

Makefile
internal/application/filesystem.go
internal/move2kubeapi/move2kubeapi.go
internal/types/appmetadata.go
scripts/detectgoversion/detect.go

feat: support the new workspace folder structure

---

go.mod
go.sum
internal/filesystem/filesystem.go
internal/move2kubeapi/handlers/handlers.go
internal/move2kubeapi/handlers/plan.go
internal/move2kubeapi/handlers/projects.go

feat: use bbolt to implement proper locking while accessing the data

---

cmd/move2kubeapi/move2kubeapi.go

fix: set umask to 0 so that file and directory permissions are set correctly

---

internal/filesystem/filesystem.go
internal/move2kubeapi/handlers/inputs.go
internal/move2kubeapi/handlers/outputs.go
internal/move2kubeapi/handlers/plan.go
internal/move2kubeapi/handlers/projects.go
internal/move2kubeapi/handlers/workspaces.go

feat: show error when failing to delete a workspace or project

---

internal/filesystem/filesystem.go

fix: customizations directory path not being set correctly when using workspace inputs without project inputs

---

go.mod
go.sum

chore: update xz version

---

internal/move2kubeapi/handlers/roles.go

See https://github.com/Nerzal/gocloak/issues/306#issuecomment-998756200

chore: workaround for role attributes is not necessary anymore since the issue has been fixed

---

internal/filesystem/filesystem.go

feat: Rename rootDir in plan as sourceDir

---

cmd/move2kubeapi/move2kubeapi.go
internal/filesystem/filesystem.go
internal/types/types.go

feat: disable local execution by default

---

Dockerfile
Makefile
README.md
go.mod

Signed-off-by: Ashok Pon Kumar Sree Prakash <ashokponkumar@gmail.com>

chore: upgrade go version to 1.18

---

internal/filesystem/filesystem.go
internal/filesystem/interface.go
internal/move2kubeapi/handlers/outputs.go
internal/move2kubeapi/move2kubeapi.go

Signed-off-by: Harikrishnan Balagopal [harikrishmenon@gmail.com](mailto:harikrishmenon@gmail.com)

feat: expose the m2k graph file using the API

---

Dockerfile
Makefile

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

feat: support multi architecture image builds

---

.github/workflows/build.yml
.github/workflows/release.yml

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

fix: setup qemu and buildx to worlflows

---

.github/workflows/release.yml

chore: fix typo in workflow

---

Makefile

fix: set the source and asset files as a dependency for cross compiling

---

assets/openapi.json

fix: typos and other minor issues in the openapi.json file

---

internal/filesystem/filesystem.go

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

fix: add checks back to api with customizations as choice

---

internal/filesystem/filesystem.go
internal/move2kubeapi/handlers/plan.go
internal/move2kubeapi/handlers/qa.go
internal/move2kubeapi/handlers/role-bindings.go
internal/move2kubeapi/handlers/roles.go

fix: return a HTTP error status code when the answer is invalid

---

cmd/main/move2kubeapi.go
internal/authserver/authserver.go
internal/common/oauth-oidc-uma.go
internal/common/utils.go
internal/move2kubeapi/handlers/handlers.go
internal/move2kubeapi/handlers/login.go
internal/move2kubeapi/move2kubeapi.go
internal/types/types.go

feat: add HTTPS support

---

cmd/main/move2kubeapi.go
internal/authserver/authserver.go
internal/common/constants.go
internal/filesystem/filesystem.go
internal/move2kubeapi/handlers/handlers.go
internal/move2kubeapi/handlers/middleware.go
internal/sessions/sessions.go
internal/types/types.go

feat: allow writing logs to a file, also allow cleaning up data directory on startup

---

internal/move2kubeapi/handlers/projects.go

fix: the content type was not set correctly in create and read project handlers

---

cmd/main/move2kubeapi.go
go.mod
go.sum
internal/move2kubeapi/move2kubeapi.go
internal/types/types.go

feat: add CORS support

---

internal/filesystem/filesystem.go

fix: planning fails when using a project with reference to workspace inputs

---

internal/authserver/authserver.go
internal/move2kubeapi/move2kubeapi.go

chore: fix some minor issues, better errors when OIDC and UMA endpoints are unreachable

---

assets/openapi.json

The API spec is not as should be:
```
$ --> curl -s http://localhost:8081/api/v1/workspaces/945d443d-564b-4a11-b26e-d3c5ea90189c/projects | jq .
[
{
"id": "ddf7fed3-86ab-4a56-b97a-f31a21c7b3cb",
"name": "test-project",
"description": "",
"timestamp": "2023-05-09T07:59:14.628527522Z",
"inputs": {
"b8ba6377-1511-484a-87cb-e67ad03ff84e": {
"id": "b8ba6377-1511-484a-87cb-e67ad03ff84e",
"name": "kuard.yaml",
"description": "",
"timestamp": "2023-05-09T08:14:40.490396702Z",
"type": "configs",
"normalized_name": "kuard"
}
},
"status": {
"configs": true,
"stale_plan": true
}
},
{
"id": "e8763b4b-637f-44b4-99fd-ee72eb7d6003",
"name": "My new project",
"description": "",
"timestamp": "2023-05-09T09:49:22.146056817Z"
},
{
"id": "26051a71-8fad-4970-9887-eb1038cd3912",
"name": "My new project", …
```

fix: openapi for getprojects fixes

---

assets/openapi.json

The current output is the following:
```
$ --> curl http://localhost:8081/api/v1/workspaces/b89dbbbd-0d9c-4fd3-965f-de94b5d9974c/projects/b013587c-06a9-45a7-a6b2-32c5259a356f  | jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   778  100   778    0     0   364k      0 --:--:-- --:--:-- --:--:--  759k
{
"id": "b013587c-06a9-45a7-a6b2-32c5259a356f",
"name": "WorkFlowID: 7ee4b05b-1bad-43d7-a121-a48082b1e108",
"description": "Project for workflow: 7ee4b05b-1bad-43d7-a121-a48082b1e108",
"timestamp": "2023-05-22T09:01:36.768895805Z",
"inputs": {
"9c0fe7fa-84ee-4cc5-b66b-dee164528f03": {
"id": "9c0fe7fa-84ee-4cc5-b66b-dee164528f03",
"name": "output.zip",
"description": "bar",
"timestamp": …
```

fix: Project openapi spec

---

Makefile

https://developer.apple.com/forums/thread/51828

fix: remove UPX because MacOS doesn't allow it

---

assets/openapi.json
internal/filesystem/filesystem.go
internal/filesystem/interface.go
internal/move2kubeapi/handlers/handlers.go
internal/move2kubeapi/handlers/outputs.go
internal/move2kubeapi/handlers/plan.go

feat: add query parameters to dump CLI log file into stdout
Related to https://github.com/konveyor/move2kube-api/issues/159

feat: add query parameters to dump CLI log file into stdout
